/* One-off: pulls the latin woff2 files this site actually uses out of Google Fonts and writes
   public/fonts/ plus public/css/fonts.css. Re-run only if the typefaces change.

   Run from the worktree root:  node tools/fetch-fonts.mjs

   All three families (Rye, Zilla Slab, JetBrains Mono) are under the SIL Open Font License, which
   permits self-hosting -- that is the whole point of the licence. */
import fs from "node:fs";
import crypto from "node:crypto";
import path from "node:path";

const HREF =
  "https://fonts.googleapis.com/css2?family=Rye&family=Zilla+Slab:ital,wght@0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@400;600&display=swap";
// A modern UA is what makes Google serve woff2 rather than a legacy format.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";

const fontsDir = path.resolve("public/fonts");
fs.mkdirSync(fontsDir, { recursive: true });
// Start clean, or renaming a hashed file would leave its predecessor behind for ever.
for (const f of fs.readdirSync(fontsDir)) fs.unlinkSync(path.join(fontsDir, f));

const css = await (await fetch(HREF, { headers: { "User-Agent": UA } })).text();

/* Google emits each face preceded by a subset comment (/* latin *\/, /* cyrillic *\/ ...). Only
   latin is kept: the park's site is in English, and shipping Cyrillic and Vietnamese would be most
   of the weight for none of the benefit. */
const blocks = css
  .split("/*")
  .slice(1)
  .map((chunk) => {
    const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
    const body = chunk.slice(chunk.indexOf("*/") + 2);
    return { subset, body };
  })
  .filter((b) => b.subset === "latin");

const out = [
  "/* Self-hosted so the site makes no third-party request at all -- see the note in",
  "   public/privacy.html. Generated by tools/fetch-fonts.mjs; don't hand-edit. */",
  "",
];

let n = 0;
for (const { body } of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
  const weight = /font-weight:\s*(\d+)/.exec(body)?.[1] ?? "400";
  const style = /font-style:\s*(\w+)/.exec(body)?.[1] ?? "normal";
  const url = /url\((https:[^)]+\.woff2)\)/.exec(body)?.[1];
  const range = /unicode-range:\s*([^;]+);/.exec(body)?.[1];
  if (!family || !url) continue;

  const bytes = Buffer.from(await (await fetch(url, { headers: { "User-Agent": UA } })).arrayBuffer());
  /* The filename carries a content hash, so a font file is immutable at its URL and can be cached
     for a year. The asset versioner only rewrites URLs it finds in the HTML, and these are
     referenced from inside fonts.css -- so without the hash there would be no way to retire a
     stale font from a cache. Same problem, same fix, different layer. */
  const hash = crypto.createHash("sha1").update(bytes).digest("hex").slice(0, 8);
  const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}${style === "italic" ? "-italic" : ""}.${hash}.woff2`;
  fs.writeFileSync(path.join(fontsDir, slug), bytes);
  n += 1;
  console.log(`  ${slug.padEnd(30)} ${(bytes.length / 1024).toFixed(1)} KB`);

  out.push(
    "@font-face {",
    `  font-family: '${family}';`,
    `  font-style: ${style};`,
    `  font-weight: ${weight};`,
    /* swap, as the Google CSS asked for: the park's copy should be readable in the fallback face
       while the webfont loads, rather than invisible. */
    "  font-display: swap;",
    `  src: url('/fonts/${slug}') format('woff2');`,
    ...(range ? [`  unicode-range: ${range};`] : []),
    "}",
    ""
  );
}

fs.writeFileSync(path.resolve("public/css/fonts.css"), out.join("\n"));
const total = fs.readdirSync(fontsDir).reduce((a, f) => a + fs.statSync(path.join(fontsDir, f)).size, 0);
console.log(`\n${n} faces, ${(total / 1024).toFixed(1)} KB total -> public/fonts/`);
console.log(`public/css/fonts.css written (${fs.statSync(path.resolve("public/css/fonts.css")).size} bytes)`);
